// SPDX-License-Identifier: GPL-3.0-or-later
using System.Text;
using Core.Mapping;

namespace Infrastructure.Yaml;

/// <summary>
/// Emits a fresh weasel.custom.yaml (§13.1): UTF-8 without BOM, consistent LF
/// newlines, deterministic key order and proper escaping of dynamic strings.
/// </summary>
public static class WeaselYamlWriter
{
    public static string Write(WeaselTheme theme, string toolVersion)
    {
        var sb = new StringBuilder();
        sb.Append("# Generated by ssf2weasel ").Append(toolVersion).Append('\n');
        sb.Append("# Managed keys are overwritten on the next conversion of the same skin.\n");
        sb.Append("patch:\n");

        foreach (var (path, value) in WeaselPatchBuilder.Build(theme))
        {
            WriteEntry(sb, path, value, indent: 1);
        }

        return sb.ToString();
    }

    private static void WriteEntry(StringBuilder sb, string key, YamlValue value, int indent)
    {
        sb.Append(new string(' ', indent * 2));
        sb.Append(QuoteKey(key)).Append(':');

        switch (value)
        {
            case YamlString s:
                sb.Append(' ').Append(QuoteString(s.Value)).Append('\n');
                break;
            case YamlRaw r:
                sb.Append(' ').Append(r.Value).Append('\n');
                break;
            case YamlMap m:
                sb.Append('\n');
                foreach (var (childKey, childValue) in m.Entries)
                {
                    WriteEntry(sb, childKey, childValue, indent + 1);
                }

                break;
            default:
                throw new InvalidOperationException($"Unknown YAML value type {value.GetType()}.");
        }
    }

    private static string QuoteKey(string key)
        => NeedsQuoting(key) ? QuoteString(key) : key;

    private static bool NeedsQuoting(string key)
        => key.Length == 0 || !key.All(c => char.IsAsciiLetterOrDigit(c) || c is '_' or '/' or '.' or '-');

    /// <summary>YAML double-quoted style escaping for arbitrary dynamic strings (§13.1).</summary>
    internal static string QuoteString(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                default:
                    if (char.IsControl(ch))
                    {
                        sb.Append("\\u").Append(((int)ch).ToString("x4"));
                    }
                    else
                    {
                        sb.Append(ch);
                    }

                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }
}
