<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Ssf2Weasel.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ssf2Weasel.Core\Ssf2Weasel.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Ssf2Weasel.TestSupport" />
    <InternalsVisibleTo Include="Ssf2Weasel.UnitTests" />
    <InternalsVisibleTo Include="Ssf2Weasel.IntegrationTests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>
